"""add item tracking_method and is_low

Revision ID: 7400f89d7aa4
Revises: 3489a3cfc89a
Create Date: 2026-01-21 13:40:08.128570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7400f89d7aa4'
down_revision = '3489a3cfc89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_method', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('is_low', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('is_low')
        batch_op.drop_column('tracking_method')

    # ### end Alembic commands ###
